version: "3"

services:
  app:
    build: .
    links:
      - db
    ports:
      - "4000:4000"
  db:
    image: mysql:5.7
    ports:
      - "3200:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurante_solid
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

